name: Maven Build

on: [push, pull_request]

jobs:
  build:
    if: "! contains(toJSON(github.event.commits.*.msg), '[CI SKIP]')"
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        java: [8]

    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: java -version && mvn --version
    - run: mvn --activate-profiles dist --no-transfer-progress package
